import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const docsDir = path.join(root, 'docs');
const pageDir = path.join(docsDir, 'page');
const postsPerPage = 10;
const generatedNotice = '<!-- This file is generated by scripts/generate-index.mjs. -->';

function parseFrontmatter(content, fallbackTitle) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) {
    return { data: { title: fallbackTitle }, body: content };
  }

  const data = { title: fallbackTitle };
  for (const line of match[1].split(/\r?\n/)) {
    const field = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!field) continue;
    const [, key, rawValue] = field;
    const value = rawValue.trim();
    if (key === 'title') data.title = value || fallbackTitle;
    if (key === 'date') data.date = value;
    if (key === 'tags' && value) data.tags = value;
  }

  return {
    data,
    body: content.slice(match[0].length),
  };
}

function excerpt(markdown) {
  const text = markdown
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/\$\$[\s\S]*?\$\$/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]+\)/g, ' ')
    .replace(/\[[^\]]+\]\([^)]+\)/g, (match) => match.match(/\[([^\]]+)\]/)?.[1] ?? ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/[#>*_`~$|[\]()-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  return text.length > 120 ? `${text.slice(0, 120)}...` : text;
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function postUrl(filename) {
  return `/${encodeURI(path.basename(filename, '.md'))}`;
}

function pageUrl(pageNumber) {
  return pageNumber === 1 ? '/' : `/page/${pageNumber}`;
}

function dateTime(date) {
  return escapeHtml(date || '');
}

function dateLabel(date) {
  return escapeHtml((date || '').split(' ')[0]);
}

function renderPost(post) {
  return `  <article class="post-card">
    <a class="post-title" href="${post.link}">${escapeHtml(post.title)}</a>
    <time datetime="${dateTime(post.date)}">${dateLabel(post.date)}</time>
    <p>${escapeHtml(post.excerpt)}</p>
    <a class="post-more" href="${post.link}">阅读全文</a>
  </article>`;
}

function renderPagination(currentPage, totalPages) {
  const controls = [];

  if (currentPage > 1) {
    controls.push(`<a href="/">首页</a>`);
    controls.push(`<a href="${pageUrl(currentPage - 1)}">上一页</a>`);
  }

  for (let page = 1; page <= totalPages; page += 1) {
    if (page === currentPage) {
      controls.push(`<span class="current">${page}</span>`);
    } else {
      controls.push(`<a href="${pageUrl(page)}">${page}</a>`);
    }
  }

  if (currentPage < totalPages) {
    controls.push(`<a href="${pageUrl(currentPage + 1)}">下一页</a>`);
  }

  return `<nav class="pagination" aria-label="文章分页">
  ${controls.join('\n  ')}
</nav>`;
}

function renderPage(posts, currentPage, totalPages) {
  const title = currentPage === 1 ? '最近文章' : `最近文章 · 第 ${currentPage} 页`;
  return `---
aside: false
---

${generatedNotice}

# ${title}

<section class="post-list">
${posts.map(renderPost).join('\n')}
</section>

${renderPagination(currentPage, totalPages)}
`;
}

const files = fs.readdirSync(docsDir)
  .filter((name) => name.endsWith('.md'))
  .filter((name) => name !== 'index.md')
  .sort();

const posts = files.map((filename) => {
  const filePath = path.join(docsDir, filename);
  const content = fs.readFileSync(filePath, 'utf8');
  const fallbackTitle = path.basename(filename, '.md');
  const parsed = parseFrontmatter(content, fallbackTitle);
  const timestamp = parsed.data.date ? new Date(parsed.data.date).getTime() : Number.NEGATIVE_INFINITY;

  return {
    filename,
    title: parsed.data.title || fallbackTitle,
    date: parsed.data.date || '',
    timestamp: Number.isNaN(timestamp) ? Number.NEGATIVE_INFINITY : timestamp,
    link: postUrl(filename),
    excerpt: excerpt(parsed.body),
  };
});

posts.sort((a, b) => {
  if (b.timestamp !== a.timestamp) return b.timestamp - a.timestamp;
  return a.title.localeCompare(b.title, 'zh-CN');
});

const totalPages = Math.max(1, Math.ceil(posts.length / postsPerPage));

fs.rmSync(pageDir, { recursive: true, force: true });
fs.mkdirSync(pageDir, { recursive: true });

for (let page = 1; page <= totalPages; page += 1) {
  const start = (page - 1) * postsPerPage;
  const pagePosts = posts.slice(start, start + postsPerPage);
  const output = renderPage(pagePosts, page, totalPages);
  const target = page === 1 ? path.join(docsDir, 'index.md') : path.join(pageDir, `${page}.md`);
  fs.writeFileSync(target, output, 'utf8');
}

console.log(`Generated ${totalPages} index pages for ${posts.length} posts.`);
